app_poller/urls.py
from app_poller import views
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static

app_name = 'app_poller'

urlpatterns = [
    path('', views.home, name='home'),
    path('signin/', views.signin, name='signin'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/profile/', views.dashboard_profile, name='dashboard_profile'),
    path('dashboard/questions/', views.dashboard_questions, name='dashboard_questions'),
    path('dashboard/questions/create/', views.dashboard_questions_create, name='dashboard_questions_creaete'),
    path('dashboard/questions/delete/<int:id>/', views.dashboard_questions_delete, name='dashboard_questions_delete'),
    path('dashboard/questions/edit/<int:id>/', views.dashboard_questions_edit, name='dashboard_questions_edit'),
    path('dashboard/polls/', views.dashboard_polls, name='dashboard_polls'),
    path('dashboard/polls/create/', views.dashboard_polls_create, name='dashboard_polls_create'),
    path('dashboard/polls/delete/<int:id>/', views.dashboard_polls_delete, name='dashboard_polls_delete'),
    path('dashboard/polls/edit/<int:id>/', views.dashboard_polls_edit, name='dashboard_polls_edit'),
    path('dashboard/tests/', views.dashboard_tests, name='dashboard_tests'),
    path('dashboard/tests/take/<int:id>/', views.dashboard_tests_take, name='dashboard_tests_take'),
    path('dashboard/answers/', views.dashboard_answers, name='dashboard_answers'),
    path('dashboard/answers/<int:id>/', views.dashboard_answers_id, name='dashboard_answers_id'),
    path('dashboard/answers/<int:id>/<int:userid>/', views.dashboard_answers_user, name='dashboard_answers_user'),
    path('dashboard/users/', views.dashboard_users, name='dashboard_users'),
    path('dashboard/users/<int:id>/', views.dashboard_users_edit, name='dashboard_users_edit'),
    # path('reset_password/', views.reset_password, name='reset_password'),
    # path('reset_password/<str:link>/', views.reset_password_link, name='reset_password_link'),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'app_poller.views.handler404'
handler500 = 'app_poller.views.handler500'

poller/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
        path('', include('app_poller.urls', namespace='app_poller')),
]

app_poller/models.py
import json
import datetime
import time

from django.contrib.postgres.fields import JSONField
from django.db import models
from django.contrib.auth.models import User
from django.contrib import messages
from django.http import Http404  


# Create your models here.


class Question(models.Model):
    title = models.CharField(max_length=130)
    body = JSONField()
    image = models.ImageField(upload_to='db_images/', default=None, blank=True)
    owned = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def getAllQuestions():
        questions = Question.objects.all()
        for question in questions:
            question.body = json.loads(question.body)
        return questions

    
    def createQusetion(request):
        title = request.POST.get('title')
        owned = User.objects.get(id=request.user.id)
        image = request.FILES.get('image')
        option = list(filter(None, request.POST.getlist('option')))
        right_answer = []
        ra = request.POST.getlist('right')
        for x in ra:
            right_answer.append(int(x))
        is_several = request.POST.get('is_several')
        body = {"option": option, "right_answer": right_answer, "is_several": is_several}
        Question(title=title, body=json.dumps(body), image=image, owned=owned).save()


    def deleteQuestion(id):
        Question.objects.filter(id=id).delete()


    def editQuestion(request, id):
        title = request.POST.get('title')
        image = request.FILES.get('image')
        option = list(filter(None, request.POST.getlist('option')))
        right_answer = []
        ra = request.POST.getlist('right')
        for x in ra:
            right_answer.append(int(x))
        is_several = request.POST.get('is_several')
        body = {"option": option, "right_answer": right_answer, "is_several": is_several}
        model = Question.objects.get(id=id)
        model.title = title
        if image != None:
            model.image = image
        model.body = json.dumps(body)
        model.save()


    def getEditQuestion(id):
        question = Question.objects.filter(id=id).first()
        if question == None:
            return None
        else:
            question.body = json.loads(question.body)
            count_option = 10 - len(question.body["option"])
            for i in range(count_option):
                question.body['option'].append('')
            return question


class Poll(models.Model):
    title = models.CharField(max_length=130)
    questions = models.ManyToManyField(Question)
    owned = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    publishing_time = models.DateField(default=None, null=True, blank=True)
    finishing_time = models.DateField(default=None, null=True, blank=True)
    time_to_answer = models.IntegerField(default=None, null=True, blank=True)
    points = JSONField()

    def __str__(self):
        return self.title

    def getAllPolls():
        polls = Poll.objects.all()
        return polls


    def getPollById(id):
        poll = Poll.objects.filter(id=id).first()
        if poll == None:
            return None
        questions = poll.questions.all()
        for question in questions:
            question.body = json.loads(question.body)
        return poll, questions

    
    def createPoll(request):
        title = request.POST.get('title')
        questions = request.POST.getlist('questions')
        points = {}
        for item in questions:
            point = request.POST.get(item)
            points.update({int(item):int(point)})
        owned = User.objects.get(id=request.user.id)
        publishing_time = request.POST.get('publishing_time')
        finishing_time = request.POST.get('finishing_time')  
        time = request.POST.get('time_to_answer').split(":")
        h = int(time[0]) * 3600
        m = int(time[1]) * 60
        time_to_answer = h+m
        poll = Poll(title=title, owned=owned, publishing_time=publishing_time, finishing_time=finishing_time, time_to_answer=time_to_answer, points=points)
        poll.save()
        for question in questions:
            poll.questions.add(question)


    def deletePoll(id):
        Poll.objects.filter(id=id).delete()

    
    def editPoll(request, id):
        poll = Poll.objects.get(id=id)
        poll.title = request.POST.get('title')
        poll.publishing_time = request.POST.get('publishing_time')
        poll.finishing_time = request.POST.get('finishing_time')
        tta = request.POST.get('time_to_answer')
        ta = tta.split(":")
        h = int(ta[0]) * 3600
        m = int(ta[1]) * 60
        poll.time_to_answer = h+m
        questions = request.POST.getlist('questions')
        points = {}
        for item in questions:
            point = request.POST.get(item)
            points.update({int(item):int(point)})
        poll.points = points
        poll.save()
        poll.questions.set(questions)


    def getEditPoll(id):
        poll = Poll.objects.filter(id=id).first()
        return poll


class Answer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE)
    body = JSONField()
    total_score = models.IntegerField(default=0)
    max_score = models.IntegerField(default=0)
    percent = models.IntegerField(default=0)
    
    
    def saveAnswer(request, id):
        questions = Poll.getPollById(id)
        questions_id = [str(question.id) for question in questions[1]]
        points = questions[0].points
        values = points.values()
        answer_list = []
        total_score = 0
        max_score = 0

        for n in questions_id:
            a = request.POST.getlist(n)
            for i in a:
                answer_list.append([int(s) for s in i.split() if s.isdigit()])

        for question in questions[1]:
            for item in answer_list:
                if item[0] == question.id:
                    if question.body.get('right_answer') != []:
                        if item[1] in question.body.get('right_answer'):
                            x = points.get(str(question.id))
                            total_score += x
                            break
                    else:
                        x = points.get(str(question.id))
                        total_score += x
                        break

        for value in values:
            max_score += value

        percent = round((total_score / max_score) * 100)

        user = User.objects.get(id=request.user.id)
        poll = Poll.objects.get(id=id)
        Answer(user=user, poll=poll, body=json.dumps(answer_list), total_score=total_score, max_score=max_score, percent=percent).save()

    def userCorrectAnswers(request):
        answers = Answer.objects.filter(user=request.user.id)
        max_points = 0
        points = 0
        for answer in answers:
            max_points += answer.max_score
            points += answer.total_score

        if max_points == 0:
            percent = 0
        else:
            percent = round((points / max_points) * 100)

        data = {"percent": percent, "max_score": max_points, "your_score": points}
        return data


    def correctAnswers(request):
        answers = Answer.objects.all()
        max_points = 0
        points = 0
        for answer in answers:
            max_points += answer.max_score
            points += answer.total_score

        if max_points == 0:
            return 0

        data = round((points / max_points) * 100)
        return data


    def getAllAnswers():
        answers = Answer.objects.all()
        return answers

    
    def getByPoll(id):
        answers = Answer.objects.filter(poll=id)
        return answers


    def getUserAnswer(id, userid):
        answer = Answer.objects.filter(user=userid, poll=id).first()
        if answer == None:
                raise Http404
        answer.body = json.loads(answer.body)
        return answer


    def getExistAnswer(request):
        EA = Answer.objects.filter(user=request.user.id)
        ids = []
        for item in EA:
            ids.append(item.poll.id)
        return ids

class editUser():


    def dashboard(request):
        user = User.objects.get(id=request.user.id)
        polls = Poll.objects.count()
        questions = Question.objects.count()
        answers = Answer.objects.count()
        user_answers = Answer.objects.filter(user=request.user.id).count()
        users = User.objects.count()

        max_setup = 5
        setup = 0
        if user.username != "":
            setup += 1
        if user.is_active:
            setup += 1
        if user.email != "":
            setup += 1
        if user.first_name != "":
            setup += 1
        if user.last_name != "":
            setup += 1
        profile_setup = round((setup / max_setup) * 100)


        data = {"polls": polls, "questions": questions, "answers": answers, "user_answers": user_answers, "profile_setup": profile_setup, "users": users}
        return data


    def adminEditUser(request, id):
        user = User.objects.get(id=id)
        username = request.POST.get('username')
        email = request.POST.get('email')
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        chekboxes = request.POST.getlist('checkbox')
        is_active = False
        is_staff = False
        is_superuser = False

        user.username = username
        user.email = email
        user.first_name = first_name
        user.last_name = last_name

        if 'is_active' in chekboxes:
            is_active = True
        if 'is_staff' in chekboxes:
            is_staff = True
        if 'is_superuser' in chekboxes:
            is_superuser = True
        
        user.is_active = is_active
        user.is_staff = is_staff
        user.is_superuser = is_superuser
        user.save()


    def profileSetup(request):

app_poller/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False)
    last_name = forms.CharField(max_length=30, required=False)
    email = forms.EmailField(max_length=254)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'first_name', 'last_name')

app_poller/templates/dashboard/polls_create.html
{% extends 'dashboard.html' %}
{% block content %}
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Create poll</h1>
</div>

<div class="row">
    <div class="col-12">
        <div class="card shadow mb-4">
            <div class="row align-items-center justify-content-center">
                <div class="col-7 mb-3 mt-3">
                    <form method="post">
                        {% csrf_token %}
                        
                            <div class="form-group">
                                <label class="text" for="id_title">Title</label>
                                <input type="text" class="form-control col-11" name="title" autofocus="" maxlength="120" required id="id_title">
                            </div>

                            <div class="form-group">
                                <label class="text" for="id_question">Choose questions</label>

                                <div class="input-group">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th scope="col" class="sortable">#</th>
                                                <th scope="col" class="sortable">Title</th>
                                                <th scope="col" class="sortable">Owned</th>
                                            </tr>
                                        </thead>
                                        {% for question in questions %}
                                        <tr>
                                            <th scope="col" class="sortable"><input type="checkbox" name="questions" value="{{ question.id }}" title="Add this question" class="form-control col-1 checkbox" style="max-width: 25px; max-height: 25px;"></th>
                                            <th scope="col" class="sortable">{{ question.title }}</th>
                                            <th scope="col" class="sortable">{{question.owned}}</th>
                                        </tr>
                                        {% endfor %}
                                    </table>
                                </div>
                            </div>
                        
                            <button type="submit" class="btn text btn-outline-dark" id="login-button">Create</button>
                        
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app_poller/templates/dashboard/polls_edit.html
{% extends 'dashboard.html' %}
{% block content %}
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Edit poll</h1>
</div>

<div class="row align-items-center justify-content-center">
    <div class="col-lg-6 col-md-10 col-sm-12">
        <div class="card shadow mb-4">
            <div class="row">
                <div class="col-12 mb-3 mt-3">
                    <form method="post">
                    {% csrf_token %}
                        <div class="form-group col-12">
                            <label class="text" for="id_title">Title</label>
                            <input type="text" class="form-control col-11" value="{{ poll.title }}" name="title" autofocus="" maxlength="120" required id="id_title">
                        </div>

                        <div class="form-group col-12">
                            <label class="text" for="id_question">Choose questions</label>

                            <div class="input-group col-12">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th scope="col" class="sortable">#</th>
                                            <th scope="col" class="sortable">Title</th>
                                            <th scope="col" class="sortable"title="Points per question">Point</th>
                                        </tr>
                                    </thead>
                                    {% for question in questions %}
                                    <tr>
                                        <th scope="col" class="sortable"><input type="checkbox" onclick="enableIn({{ question.id }})" name="questions" value="{{ question.id }}" {% if question.id in ids %}checked{% endif %} title="Add this question" class="form-control col-1 checkbox" style="max-width: 25px; max-height: 25px;"></th>
                                        <th scope="col" class="sortable">{{ question.title }}</th>
                                        <th scope="col" class="sortable"><input type="number" id="{{ question.id }}" {% if question.id not in ids %} disabled {% endif %} name="{{question.id}}"
                                        {% for key, value in poll.points.items %}
                                        {% if key == question.id|slugify %}
                                        value="{{value}}"
                                        {% endif %}
                                        {% endfor %}
                                        min=0 max=100 value="1" title="Points per question"></th>
                                    </tr>
                                    {% endfor %}
                                </table>
                            </div>

                            <div class="form-group">
                                <label class="text" for="id_title">Publishing date</label><br>
                                <input type="date" name="publishing_time" value="{{ poll.publishing_time|date:'Y-m-d' }}">
                            </div>

                            <div class="form-group">
                                <label class="text" for="id_title">Finishing date</label><br>
                                <input type="date" name="finishing_time" value="{{ poll.finishing_time|date:'Y-m-d' }}">
                            </div>

                            <div class="form-group">
                                <label class="text" for="id_title">Time to answer</label><br>
                                <input type="time" name="time_to_answer" value="{{ poll.time_to_answer }}" title="Hour\Min  00:00 - no limit">
                            </div>
                        </div>
                        
                        <button type="submit" class="btn text btn-outline-dark ml-3 mt-2" id="login-button">Update</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script defer type="text/javascript">
    function enableIn(inputId) {
        let input = document.getElementById(inputId);
        if (input.disabled === false) {
            input.disabled = true;
        }
        else if (input.disabled === true) {
            input.disabled = false;
        }
}
</script>
{% endblock %}

app_poller/templates/dashboard/profile.html
{% extends 'dashboard.html' %}
{% block content %}
<!-- Page Heading -->
<div class="col-7 d-sm-flex align-items-center justify-content-betwen mb-4">
  <h1 class="h3 mb-0 text-gray-800">Profile</h1>
</div>

<div class="row align-items-center justify-content-center">
    <div class="col-lg-6 col-md-10 col-sm-12">
        <div class="card shadow mb-4">
            <div class="row">
                <div class="col-12 mt-3">
                    <form method="POST" name="editProfile" action="">
                    {% csrf_token %}
                        <div class="form-group col-12">
                            <label class="text" for="username">Username</label>
                            <input type="text" class="form-control" name="username" value="{{ request.user.username }}" required id="username" disabled>
                            <p class="text font-weight-light mt-1 ml-1"><small>You can change <a href="" data-toggle="modal" data-target="#editUsername">username</a> or <a class="" href="" data-toggle="modal" data-target="#editPassword">password</a></small></p>
                        </div>

                        <div class="form-group col-12">
                            <label class="text">Email</label>
                            <input type="text" class="form-control" value="{{ request.user.email }}" disabled>
                            <p class="text font-weight-light mt-1 ml-1"><small>Also you can change <a href="" data-toggle="modal" data-target="#editEmail">email</a></small></p>
                        </div>

                        <div class="form-group col-12">
                            <label class="text" for="first_name">First name</label>
                            <input type="text" class="form-control" name="first_name" value="{{ request.user.first_name }}" id="first_name">
                        </div>

                        <div class="form-group col-12">
                            <label class="text" for="last_name">Last name</label>
                            <input type="text" class="form-control" name="last_name" value="{{ request.user.last_name }}" id="last_name" >
                        </div>

                        <button type="submit" class="btn text btn-outline-dark ml-3 mt-2" name="editProfile" value="True">Update name</button>

                        <hr>

                        <div class="form-group col-12">
                            <p class="text">Date joined: {{ request.user.date_joined }}</p>
                        </div>

                        <div class="form-group col-12">
                            <p class="text">Id: {{ request.user.id }}</p>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="editUsername" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" style="display: none;" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">

            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Change username</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>

            <div class="modal-body">
                <form method="POST" name="editUsername" action="">
                {% csrf_token %}
                    <div class="form-group">
                        <label class="text" for="id_password1">New username</label>
                        <input type="text" class="form-control inputs" name="username" autocomplete="off" required id="id_username1">
                        {% if messages %}{% for message in messages %}<p class="text font-weight-light mt-1 ml-1">{{ message }}</p>{% endfor %}{% endif %}
                    </div>
                    <button type="submit" class="btn text btn-outline-dark" name="editUsername" value="True">Change username</button>
                </form>
            </div>

        </div>
    </div>
</div>

<div class="modal fade" id="editPassword" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" style="display: none;" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">

            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Change password</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>

            <div class="modal-body">
                <form method="POST" name="editPassword" action="">
                {% csrf_token %}
                    <div class="form-group">
                        <label class="text" for="id_password1">New password</label>
                        <input type="password" minlength="4" class="form-control inputs" name="password" autocomplete="new-password" required id="id_password1" minlength="8" aria-autocomplete="list">
                    </div>

                    <div class="form-group">
                        <label class="text" for="id_password2">Repeat password</label>
                        <input type="password" minlength="4" class="form-control inputs" name="password" autocomplete="new-password" required id="id_password2" minlength="8" aria-autocomplete="list">
                    </div>
                    <p class="text font-weight-light mt-1 ml-1"><small>Min lenght: 4</small></p>
                    <button type="submit" class="btn text btn-outline-dark" name="editPassword" value="True">Change password</button>
                </form>
            </div>

        </div>
    </div>
</div>

<div class="modal fade" id="editEmail" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" style="display: none;" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">

            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Change email</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>

            <div class="modal-body">
                <form method="POST" name="editEmail" action="">
                {% csrf_token %}
                    <div class="form-group">
                        <label class="text" for="id_email">New email</label>
                        <input type="email" class="form-control inputs" name="new_email" required id="id_email">
                    </div>

                    <button type="submit" class="btn text btn-outline-dark" name="editEmail" value="True">Change email</button>
                </form>
            </div>

        </div>
    </div>
</div>
{% endblock %}

app_poller/templates/dashboard/questions_edit.html
{% extends 'dashboard.html' %}
{% block content %}
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Edit question</h1>
</div>

<div class="row align-items-center justify-content-center">
    <div class="col-lg-7 col-md-10 col-sm-12">
        <div class="card shadow mb-4">
            <div class="row">
                <div class="col-12 mb-3 mt-3">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        
                            <div class="form-group col-12">
                                <label class="text" for="id_title">Question</label>
                                <input type="text" class="form-control col-11" value="{{ questions.title }}" name="title" autofocus="" maxlength="120" required id="id_title">
                            </div>

                            <div class="form-group col-12">
                                <label class="text" for="id_question">Answer options</label>
                                {% for question in questions.body.option %}
                                <div class="input-group">
                                    <input type="textarea" class="form-control mb-2" name="option" id="id_question" placeholder="{% cycle '1 option' '2 option' '3 option' '4 option' '5 option' '6 option' '7 option' '8 option' '9 option' '10 option' as num %}" value="{{ question }}" {% if num == "1 option" or num == "2 option" %}required{% endif %}>
                                    <input type="checkbox" name="right" title="Is this option right?" class="form-control col-1 ml-2 checkbox" value="{% cycle 0 1 2 3 4 5 6 7 8 9 as val %}"  {% if val in questions.body.right_answer %}checked{% endif %}>
                                </div>
                                {% endfor %}
                            </div>

                            <div class="form-group col-12">
                                <div class="input-group">
                                    <span class="text" for="">May choose several:</span>
                                    <input type="checkbox" name="is_several" value="True" class="form-control col-1 ml-2" style="height: 20px;" {% if questions.body.is_several == "True" %}checked{% endif %}>
                                </div>
                            </div>
                            
                            <div class="form-group col-12">
                                <div class="input-group">
                                    <span class="text" for="">Picture: </span>
                                    <input type="file" accept="image/*" name="image" class="col-1 ml-2" >
                                </div>
                            </div>

                            <button type="submit" class="btn text btn-outline-dark  ml-3 mt-2" id="login-button">Update</button>
                        
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}